name: flutter_starter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  dartz: ^0.10.1
  dio: ^5.1.1

  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_phoenix: ^1.1.1
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^7.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.0
  path_provider: ^2.0.14

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/img/
  fonts:
    - family: Trueno
      fonts:
        - asset: assets/fonts/trueno/TruenoBd.otf
        - asset: assets/fonts/trueno/TruenoBdIt.otf
        - asset: assets/fonts/trueno/TruenoBdOl.otf
        - asset: assets/fonts/trueno/TruenoBdOlIt.otf
        - asset: assets/fonts/trueno/TruenoBlk.otf
        - asset: assets/fonts/trueno/TruenoBlkIt.otf
        - asset: assets/fonts/trueno/TruenoBlkOl.otf
        - asset: assets/fonts/trueno/TruenoBlkOlIt.otf
        - asset: assets/fonts/trueno/TruenoExBd.otf
        - asset: assets/fonts/trueno/TruenoExBdIt.otf
        - asset: assets/fonts/trueno/TruenoExBdOl.otf
        - asset: assets/fonts/trueno/TruenoExBdOlIt.otf
        - asset: assets/fonts/trueno/TruenoLt.otf
        - asset: assets/fonts/trueno/TruenoLtIt.otf
        - asset: assets/fonts/trueno/TruenoRg.otf
        - asset: assets/fonts/trueno/TruenoRgIt.otf
        - asset: assets/fonts/trueno/TruenoSBd.otf
        - asset: assets/fonts/trueno/TruenoSBdIt.otf
        - asset: assets/fonts/trueno/TruenoUltBlk.otf
        - asset: assets/fonts/trueno/TruenoUltBlkIt.otf
        - asset: assets/fonts/trueno/TruenoUltLt.otf
        - asset: assets/fonts/trueno/TruenoUltLtIt.otf
    - family: ActionSans
      fonts:
        - asset: assets/fonts/action-sans/ActionSans-Bold.otf
        - asset: assets/fonts/action-sans/ActionSans-Light.otf
        - asset: assets/fonts/action-sans/ActionSans-Medium.otf
        - asset: assets/fonts/action-sans/ActionSans-Regular.otf
